### ISSUE TITLE
Project Idea: Compare Tracing API outputs across clients

### ISSUE THREAD

**Issue by timbeiko** [eth-protocol-fellows/cohort-one#43]
One of the main reason for the "stickiness" of clients is their tracing APIs. When sophisticated users (e.g. exchanges, block explorers, infrastructure providers, etc.) need to read the data from Ethereum, not only do they need the full blocks/transactions, but they also require the entire traces for them. Different clients provide different ways to access these traces, and applications tend to be built around their client of choice's specific output. 

To make it easier for users to swap clients, ideally these trace formats would be standardized. A first step towards getting there, is having a clear view of the various tracing APIs across clients, and how their output differs. At a high level, what I would suggest is: 

1. Review the various APIs available in [go-ethereum](https://geth.ethereum.org/docs/dapp/tracing), [Open Ethereum](https://openethereum.github.io/JSONRPC-trace-module), [Nethermind](https://docs.nethermind.io/nethermind/nethermind-utilities/cli/trace), [Erigon](https://github.com/ledgerwatch/erigon/issues/1119) and [Besu](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#trace-methods). 
2. Create a table listing which clients support which tracing modes (and ideally the different method name for each client). 
3. For the API calls which are supported across multiple clients, trace the last ~100,000 blocks on mainnet using each client and document any inconsistencies in the results.

**Comment by hansmrtn** [comment]
Hey @timbeiko I'd like take on this project👍!

**Comment by jp4ducks** [comment]
@timbeiko @hansmrtn Sounds super interesting for me too! A mix of market research, documentation and a real use case. How we might proceed?

**Comment by pipermerriam** [comment]
Possible step 4: Write an EIP which defines a standard for tracing APIs

**Comment by timbeiko** [comment]
@pipermerriam that has been tried (https://eips.ethereum.org/EIPS/eip-3155) but it never really took off. I think it's probably easier at this point to document the differences and then either clients can harmonize (and then we can write an EIP which describes things as they are vs. "as we'd like them to be"), or users can know how to handle the various edge cases 😅

**Comment by yoavw** [comment]
It seems hardhat has done a good job mapping out the differences.  When using tools that don't work well with a specific node version (e.g. Brownie not parsing Erigon's traces correctly), I found that putting a hardhat fork between the node and the tool often solves the problem.  Hardhat "normalizes" the trace.

**Comment by JEAlfonsoP** [comment]
I would like to help on this 100% !

**Comment by JEAlfonsoP** [comment]
👍🏻

**Comment by hansmrtn** [comment]
Here is a repo that we can work on: Please fork it and PR if you'd like to contribute https://github.com/hansmrtn/evm-tracing-comparison 😄

**Comment by tjayrush** [comment]
We (TrueBlocks) are also interested in this. We have both OpenEtheruem and Erigon archive nodes running and have been doing a lot of testing against both. Over about 300 tests across all the `trace_*` routines, we find no discrepancies (although the testing is not complete).

Recently, we scraped all 13,400,000 blocks using `trace_block` and found perfect duplication between Erigon and OpenEthereum for every block but ONE. In that one block, there was ONE trace different. That's a single difference across possibly as many as billions of traces.

I think it would be good to start with a **gold standard** for the `trace_` routines, and I would suggest Erigon be that gold standard given that OpenEthereum will be disappearing soon.
